### ISSUE TITLE
placeholder not changing on React 17

### ISSUE THREAD

**Issue by RobbStarkAustria** [hcoz/react-context-multilang#5]
Hi,

I used your code for implementing multilanguage functionality to my webpage. I use React 17 and react-bootstrap latest release.

Switching the language works fine for the <Text>-token, but the dictonary entry would not be changed.

Your project from this github with React 16 works well, also on placeholders.

My transfer to React 17 struggles with the rendering of dictonary entries.

Using Webstorm the function `userLanguageChange` is marked as unused property in `Language.js`.

For your information; I use the same folder structure instead of `components` for my pages.

Any suggestions for this issue?

Thank you in advance!

**Comment by hcoz** [comment]
Hi,
I upgraded the project repo to React 17. I can't see any problem. Also, [demo website](https://nice-cliff-047044a03.azurestaticapps.net) added. Feel free to examine it.

`userLanguageChange` is for handling language selector change. It is triggered on every language selection as you can see by debugging. Honestly, I have no idea how it can be unused.

If you still have any question please elaborate it.
Thanks!
